export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';
export const ATIVAR_NAV = 'ATIVAR_NAV ';
export const DESATIVAR_NAV = 'DESATIVAR_NAV ';
